import Loader from "@/components/Loader";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<Suspense fallback={<Loader className="mx-auto w-12 h-12 mt-10 " />}>
					{children}
				</Suspense>
			</body>
		</html>
	);
}
